In [10]:
import numpy as np

In [11]:
dt = np.dtype(np.int32)
print(dt)

int32


In [12]:
a = np.array([1,2,3],[4,5,6])
b = a.shape = (3,2)
print(b)

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [13]:
a = np.arange(24)

In [14]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [15]:
b = a.reshape(2,4,3)
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [16]:
print(b.itemsize)

4


In [21]:
x = [1,2,3]
a = np.asarray(x)
print(a)

[1 2 3]


In [26]:
a = np.array([[1,2,3],[4,5,6], [7,8,9]])

In [29]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
print(a[...,1])

[2 5 8]


In [28]:
print(a[1,...])

[4 5 6]


In [30]:
print(a[...,1:])

[[2 3]
 [5 6]
 [8 9]]
